<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    <InternalsVisibleTo Include="CodeReviewInsight.Api.Tests" />
    <InternalsVisibleTo Include="CodeReviewInsight.Domain.Tests" />
    <InternalsVisibleTo Include="CodeReviewInsight.AzureDevopsItg.Tests" />
    <InternalsVisibleTo Include="CodeReviewInsight.Database.Tests" />
  </ItemGroup>
</Project>